package cc.mobireach.api.model;
// Generated 24-Oct-2016 18:15:56 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BrandAdmin generated by hbm2java
 */
@Entity
@Table(name = "BrandAdmin", catalog = "estorywo_webapp")
public class BrandAdmin implements java.io.Serializable {

	private Integer brandAdminId;
	private Brand brand;
	private User user;
	private boolean active;

	public BrandAdmin() {
	}

	public BrandAdmin(Brand brand, User user, boolean active) {
		this.brand = brand;
		this.user = user;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brandAdminId", unique = true, nullable = false)
	public Integer getBrandAdminId() {
		return this.brandAdminId;
	}

	public void setBrandAdminId(Integer brandAdminId) {
		this.brandAdminId = brandAdminId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId", nullable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
