package cc.mobireach.api.model;
// Generated 24-Oct-2016 18:15:56 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "Device", catalog = "estorywo_webapp")
public class Device implements java.io.Serializable {

	private int deviceId;
	private Date createDate;

	public Device() {
	}

	public Device(int deviceId, Date createDate) {
		this.deviceId = deviceId;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "deviceId", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
