package cc.mobireach.api.model;
// Generated 24-Oct-2016 18:15:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoyaltyTransactionType generated by hbm2java
 */
@Entity
@Table(name = "LoyaltyTransactionType", catalog = "estorywo_webapp")
public class LoyaltyTransactionType implements java.io.Serializable {

	private Integer transactionTypeId;
	private String transactionType;
	private String description;
	private Set<LoyaltyTransaction> loyaltyTransactions = new HashSet<LoyaltyTransaction>(0);

	public LoyaltyTransactionType() {
	}

	public LoyaltyTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public LoyaltyTransactionType(String transactionType, String description,
			Set<LoyaltyTransaction> loyaltyTransactions) {
		this.transactionType = transactionType;
		this.description = description;
		this.loyaltyTransactions = loyaltyTransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "transactionTypeId", unique = true, nullable = false)
	public Integer getTransactionTypeId() {
		return this.transactionTypeId;
	}

	public void setTransactionTypeId(Integer transactionTypeId) {
		this.transactionTypeId = transactionTypeId;
	}

	@Column(name = "transactionType", nullable = false, length = 45)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loyaltyTransactionType")
	public Set<LoyaltyTransaction> getLoyaltyTransactions() {
		return this.loyaltyTransactions;
	}

	public void setLoyaltyTransactions(Set<LoyaltyTransaction> loyaltyTransactions) {
		this.loyaltyTransactions = loyaltyTransactions;
	}

}
