package cc.mobireach.api.model;
// Generated 24-Oct-2016 18:15:56 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "Member", catalog = "estorywo_webapp")
public class Member implements java.io.Serializable {

	private Integer memberId;
	private User user;
	private String smsReceivedOn;
	private char gender;
	private Integer age;
	private Set<Subscription> subscriptions = new HashSet<Subscription>(0);

	public Member() {
	}

	public Member(User user, char gender) {
		this.user = user;
		this.gender = gender;
	}

	public Member(User user, String smsReceivedOn, char gender, Integer age, Set<Subscription> subscriptions) {
		this.user = user;
		this.smsReceivedOn = smsReceivedOn;
		this.gender = gender;
		this.age = age;
		this.subscriptions = subscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "memberId", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "smsReceivedOn", length = 45)
	public String getSmsReceivedOn() {
		return this.smsReceivedOn;
	}

	public void setSmsReceivedOn(String smsReceivedOn) {
		this.smsReceivedOn = smsReceivedOn;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Subscription> getSubscriptions() {
		return this.subscriptions;
	}

	public void setSubscriptions(Set<Subscription> subscriptions) {
		this.subscriptions = subscriptions;
	}

}
