package cc.mobireach.api.model;
// Generated 24-Oct-2016 18:15:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operator generated by hbm2java
 */
@Entity
@Table(name = "Operator", catalog = "estorywo_webapp")
public class Operator implements java.io.Serializable {

	private Integer operatorId;
	private Store store;
	private User user;
	private boolean active;
	private Set<LoyaltyTransaction> loyaltyTransactions = new HashSet<LoyaltyTransaction>(0);

	public Operator() {
	}

	public Operator(Store store, User user, boolean active) {
		this.store = store;
		this.user = user;
		this.active = active;
	}

	public Operator(Store store, User user, boolean active, Set<LoyaltyTransaction> loyaltyTransactions) {
		this.store = store;
		this.user = user;
		this.active = active;
		this.loyaltyTransactions = loyaltyTransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "operatorId", unique = true, nullable = false)
	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storeId", nullable = false)
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operator")
	public Set<LoyaltyTransaction> getLoyaltyTransactions() {
		return this.loyaltyTransactions;
	}

	public void setLoyaltyTransactions(Set<LoyaltyTransaction> loyaltyTransactions) {
		this.loyaltyTransactions = loyaltyTransactions;
	}

}
