package cc.mobireach.api.model;
// Generated 24-Oct-2016 18:15:56 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SalesRep generated by hbm2java
 */
@Entity
@Table(name = "SalesRep", catalog = "estorywo_webapp")
public class SalesRep implements java.io.Serializable {

	private Integer repId;
	private String name;
	private Set<Brand> brands = new HashSet<Brand>(0);

	public SalesRep() {
	}

	public SalesRep(String name, Set<Brand> brands) {
		this.name = name;
		this.brands = brands;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "repId", unique = true, nullable = false)
	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesRep")
	public Set<Brand> getBrands() {
		return this.brands;
	}

	public void setBrands(Set<Brand> brands) {
		this.brands = brands;
	}

}
